### ISSUE TITLE
First run check question.

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#101]
Look at the following...

https://github.com/splunk/splunk-ansible/blob/8149b68198197bbe7c3aa8be1ea30a7f63b1d80e/roles/splunk_common/tasks/main.yml#L9-L12

I'd assume this would prevent upgrades from being applied. E.g. deploying splunk/splunk:7.2.1 and then splunk/splunk:7.2.3 wouldn't actually install the new version of splunk. Is that correct? Is that expected?

**Comment by lephino** [comment]
Think this is due to: https://github.com/splunk/splunk-ansible/pull/100 not being in yet, it specifically calls out upgrade.

**Comment by lephino** [comment]
Actually, think you might be right, I don't see where we include it on upgrade.

**Comment by lephino** [comment]
https://github.com/splunk/splunk-ansible/blob/develop/site.yml#L62

**Comment by jmervine** [comment]
How does `splunk.upgrade` get set here: https://github.com/splunk/splunk-ansible/blob/develop/site.yml#L62-L67?

The only thing one should have to do to upgrade splunk is to deploy a new image.

**Comment by jmervine** [comment]
Gotcha, then this issue might be invalid. If you agree close it.

**Comment by dLabsMarijnB** [comment]
Currently it still considers it a first run based on the fact if the /opt/splunk/bin/splunk is available or not. This should be changed to verify if there is a version installed.
Next would be to change the when clause for the install.

My idea would be to trigger the install_splunk.yml task if:
It is a first run
or
it is an upgrade defined by splunk_upgrade (check if version is different) AND splunk.allow_upgrade (which is set by the user to allow or disallow upgrades)

**Comment by lephino** [comment]
@mikedickey I think this logic is met, and we can close this pr, however your pr directly hits this logic as well.  I'll leave this one to you to close.

**Comment by mikedickey** [comment]
I agree this is solved by changes in SkyKnightSKS's PR, and then tweaked a little bit in my own PR (I already merged those changes in and resolved conflicts).
