### ISSUE TITLE
Start/stop splunk tasks fail when Linux distro isn't systemd based

### ISSUE THREAD

**Issue by rcabral-splunk** [splunk/splunk-ansible#106]
For those systemv based Linux, start/stop tasks fail, since it currently only supports systemd based ones. We also need to support sytemv, for the AMI builds that make use of Amazon Linux (version 1).

**Comment by nwang92** [comment]
I believe @rcabral-splunk had some open issues with this still. Please re-open the PR when you're ready.

**Comment by SkyKnightSKS** [comment]
When using systemctl there is still an issue.  Systemctl fires off the splunkd process and continues.  But Splunk is not yet up and running.  API calls following this will not be able to connect as the process is not available to answer.

There was a wait-for-port task which was removed for UF support, a proper way to handle the wait for process part should be implemented.

**Comment by rcabral-splunk** [comment]
> When using systemctl there is still an issue. Systemctl fires off the splunkd process and continues. But Splunk is not yet up and running. API calls following this will not be able to connect as the process is not available to answer.
> 
> There was a wait-for-port task which was removed for UF support, a proper way to handle the wait for process part should be implemented.

I guess we can close this PR in favor of #115. If you are still having issues with process not able to connect, let's discuss on #115 perhaps?

**Comment by lephino** [comment]
Closing, move discussions to #115
