### ISSUE TITLE
splunk standalone failed to start if management port https disabled

### ISSUE THREAD

**Issue by kravchukkravchuk** [splunk/splunk-ansible#135]
The reason of disable https on splunkd managment port - SSL Termination is responsiility of Nginx Reverse Proxy, and I use http locally. Just I disable HTTPS splunk can't start (

1) Disable https on the splunkd management port (8089)
in `etc/system/local/server.conf`

 ```
[sslConfig]
enableSplunkdSSL = false
```
2) build docker image
```
FROM splunk/splunk:latest
COPY ./splunk-config/etc/system/local/server.conf /opt/splunk/etc/system/local/server.conf
```
3) run the new docker image

it doesnt start
```
TASK [splunk_standalone : Check for required restarts] *************************
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200, 404]: Request failed: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)>", "redirected": false, "status": -1, "url": "https://127.0.0.1:8089/services/messages/restart_required?output_mode=json"}
  to retry, use: --limit @/opt/container_artifact/ansible-retry/site.retry
medfitbi-staging_medfit-splunk.1.doba9vsufhyr@strikerops    |
PLAY RECAP *********************************************************************
localhost                  : ok=34   changed=12   unreachable=0    failed=1

```

looks like issue in hardcoded https schema in ansible task
[roles/splunk_common/tasks/check_for_required_restarts.yml](https://github.com/splunk/splunk-ansible/blob/98b742235c8cae93b7f525f378f736efc5372a0f/roles/splunk_common/tasks/check_for_required_restarts.yml#L4)

![image](https://user-images.githubusercontent.com/19905140/53972678-f1ded580-4107-11e9-90f2-d76a409958e9.png)

**Comment by lephino** [comment]
I can see how this breaks a lot, as we have https:// hard coded a lot.  Is there a reason you disable https on the splunkd port?  @mikedickey is this something we want to support?  If so, I think all the plays will need a "try https, if fails, http, if fails exit" type logic.

**Comment by mikedickey** [comment]
I don't think so, but I'm curious why someone would want to use an nginx reverse-proxy here. There may be a better way to solve for what you are trying to do.

**Comment by lephino** [comment]
Closing this issue as "won't support"
