### ISSUE TITLE
http_port value in default.yml ignored.

### ISSUE THREAD

**Issue by BertieW** [splunk/splunk-ansible#140]
Setting http_port in default.yml does nothing. The port is always 8000.

**Comment by arctan5x** [comment]
Let me take a look.

**Comment by BertieW** [comment]
We already have something serving on 8000 on that machine. It isn't anything that we can't work around but it is confusing that the ability to specify the port is there and it is a value that can be changed via the SplunkWeb or config files. 

If the script always provisions splunkweb to 8000 at boot, maybe documentation can be amended to explain that?

**Comment by gibban69** [comment]
> We already have something serving on 8000 on that machine. It isn't anything that we can't work around but it is confusing that the ability to specify the port is there and it is a value that can be changed via the SplunkWeb or config files, yet nothing is done with that info.
> 
> If the script always provisions splunkweb to 8000 at boot, maybe documentation can be amended to explain that?

I agree that it is very confusing. I takes time to discover that changing some of the values in the generated default.yml has no effect. There is no indication which ones are just ignored. I suggest the "create-defaults" commands only generates the config parameters that are not ignored.
