### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by underhill** [splunk/splunk-ansible#157]
I've spent the last couple of days hunting down docs on how to use the roles. While putting in this issue, I found another ticket which directed users to the docker-splunk project. For pete's sake, add that link to this project's docs so that other poor bastards like myself aren't wasting hours.

**Comment by arctan5x** [comment]
will do!

**Comment by arctan5x** [comment]
PR to your issue: https://github.com/splunk/splunk-ansible/pull/159
