### ISSUE TITLE
Ad-hoc plays collision

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#162]
It appears that when you have both a pre install and post install hook defined, the files defined are both written to the same location. See:
https://github.com/splunk/splunk-ansible/blob/master/execute_adhoc_plays.yml#L10

The exact issue I'm seeing is thus
1. Set pre hook to a file containing a set of plays.
1. Set post hook to a file containing a different set of plays.
1. Note that upon execution, the pre hook set of plays are executed both before and after and the post hook plays are never executed.

**Comment by nwang92** [comment]
Learning some quirks with Ansible, this should be fixed here: https://github.com/splunk/splunk-ansible/pull/163
