### ISSUE TITLE
Cluster Master requires indexer list though the indexers use CM discovery.

### ISSUE THREAD

**Issue by sharkannon** [splunk/splunk-ansible#196]
Sorry guys, you did some work for me on the Deployment server, but I haven't really had any time tot test it.  I had moved on from that and thought I'd try setting up a CM/Indexer cluster.  We're deploying this all to Kubernetes, we usually have 2-3 indexers in a region controlled by a single CM.

The problem is simple: Currently when you define a CM, it REQUIRES the list of Indexers that will connect to it (SPLUNK_INDEXER_URL).  In Kubernetes, that's actually impossible as you can't assign static IP's, plus kinda defeats the purpose of using CM Discovery (which allows you to spin up additional indexers as you wish).

Code like:

```
- name: Get indexer count
  set_fact:
    num_indexer_hosts: "{{ groups['splunk_indexer'] | length }}"
```

(And there's a test somewhere, can't find it atm, that does a quick test on each indexer to test that they are up, I think it's part of the cluster_bundle code)

This causes a massive race condition as you can't define the SPLUNK_INDEXER_URL when you don't know the count, ip's or hostnames of the indexers before they come online (And the names can change at any time).

**Comment by nwang92** [comment]
I believe the cluster master *does* use the list of indexers for the purposes of determining replication factor - this can possibly be changed such that you can provide your own count. The only downside is your desired replication count might cause errors within splunkd if you don't have enough indexers to meet your desired configuration.

Outside of that, it's actually the individual indexers that register themselves against the cluster master. See [here](https://github.com/splunk/splunk-ansible/blob/c17af71905c4ef0206bcad619e4518129940a6ed/roles/splunk_indexer/tasks/indexer_clustering.yml#L6). This is done to enable dynamic indexer creation and self-registration.

**Comment by sharkannon** [comment]
The replication count should be configured manually anyway depending on how you want things setup. If you error out your rep count that’s a different problem.

**Comment by nwang92** [comment]
Will make the relevant changes as part of https://github.com/splunk/splunk-ansible/issues/196, because both of these issues are asking for the same thing.
