### ISSUE TITLE
Outputs configuration should not use rest

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-ansible#232]
Using rest causes splunk to index locally until forwarding is enabled this is an incorrect behavior

**Comment by nwang92** [comment]
We opted for the REST API over writing conf files for the sake of backwards-compatibility + future-proofing the spec. If anything changes when writing conf files directly, there's a chance btool prevents Splunk from starting - whereas we *should* be able to expect the REST API to be consistent and handle any changes when necessary.

There's also some added benefit of REST API changes being reflected immediately vs. files on disk changes requiring a full Splunk restart. In the end, I suppose there will be a case of splunk-indexing-locally-until-forwarding-is-enabled, but this period shouldn't last very long and it comes with the tradeoff of increased start-up time.
