### ISSUE TITLE
in a cluster the indexer should not enable inputs locally

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-ansible#234]
Inputs on a clustered indexer should only be enabled via master-apps

**Comment by nwang92** [comment]
I'm guessing you're referring to HEC right now? I believe that's the only input we "enable" by default

**Comment by rfaircloth-splunk** [comment]
Both the enable s2s and enable http inputs are run on "indexer" roles indexer and indexer peers are not the same, no inputs should be enabled on a indexer peer as this will lead to data loss if as part of a cluster it does not yet have props/transforms indexes etc

**Comment by nwang92** [comment]
Splunk-to-splunk setup has been moved such that it gets created before Splunk starts. We can probably move HEC setup as well, but will address that as part of https://github.com/splunk/splunk-ansible/issues/291. Going to close this now.
