### ISSUE TITLE
Need splunk.secret as ENV Var

### ISSUE THREAD

**Issue by splunkbot9000** [splunk/splunk-ansible#253]
I would like to request the ability to specify the splunk.secret as an environment variable so it does not need to be stored in defaults.yml in cases where instances need to share it.

**Comment by nwang92** [comment]
Fixed here: https://github.com/splunk/splunk-ansible/pull/260. I'll add a test for this in the docker-splunk project

**Comment by nwang92** [comment]
This should be available in the `7.3.2` or `7.3.1.1` version tags which will be published sometime this week.
