### ISSUE TITLE
[FER]:  avoid using app:* in generate_server_classes.yml

### ISSUE THREAD

**Issue by mkinsley** [splunk/splunk-ansible#279]
Feature Enhancement Request / Opportunity for improvement

The generate_server_classes.yml play uses a wildcard app selector.   When you edit the "all" class via the UI and remove an app, it will appear to have succeeded in the UI.  When splunk restarts, it picks the apps back up again and distributes them to all clients. 

Example: 

```
[serverClass:all]
whitelist.0 = *

[serverClass:all:app:*]
restartSplunkd = true
```

If we iterate over the apps in in  /etc/deployment apps and add an explicit stanza for each app, we would maintain compatibility with the UI editor.

```
[serverClass:alll:app:my_foo_app]
[serverClass:alll:app:my_bar_app]
[serverClass:alll:app:my_baz_app]
```

**Comment by nwang92** [comment]
Fixed with https://github.com/splunk/splunk-ansible/pull/295
