### ISSUE TITLE
In a clustered ENV hec token should not be placed directly on indexers

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-ansible#291]
This allows for data loss where the input is enabled on a new indexer before indexes.conf has been deployed. When in indexer mode HEC tokens must be applied via master-apps

**Comment by nwang92** [comment]
Going to close this because the discussion thread on HEC inputs/`splunk.hec.*` is here: https://github.com/splunk/splunk-ansible/issues/439
