### ISSUE TITLE
SmartStore advanced configuration

### ISSUE THREAD

**Issue by flyingcougar** [splunk/splunk-ansible#309]
Hi,

is there a way to configure SmartStore cache manager and retention policy via splunk-ansible.
https://docs.splunk.com/Documentation/Splunk/8.0.0/Indexer/ConfigureSmartStorecachemanager

**Comment by bb03** [comment]
@flyingcougar We do, yes.  Unfortunately, the documentation seems to only be in our docker-splunk repo.  https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md#enable-smartstore

So, yeah, it should also be over in this repo.

**Comment by flyingcougar** [comment]
@bb03 Thx, I Have followed the setting there and those work. My concern is about other SmartStore options like `max_cache_size` or `minFreeSpace` - related to cache settings and the ones related to retention policies i.e `maxGlobalRawDataSizeMB`.

From what i can see in the roles, only s3 variables are moved from defaults.yml to the appropriate Splunk configs:
https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_cluster_master/tasks/configure_indexes.yml
