### ISSUE TITLE
Confusing terminology in docs/advanced/default.yml.spec.md

### ISSUE THREAD

**Issue by xpac1985** [splunk/splunk-ansible#310]
The file `docs/advanced/default.yml.spec.md` has multiple occurences of the variable `secret`.

![image](https://user-images.githubusercontent.com/6882771/69727280-84098c80-1122-11ea-9fc9-98c66bfa0fcf.png)

The upper one correctly describes it's usage to fill the `splunk.secret` file.
The lower one correctly describes what is usually called the `pass4SymmKey` in Splunk context, but doesn't mention it. Instead, the term `secret` is used again, as also (sadly) happens in the Splunk docs.

If somebody scans the spec file for a way to change the pass4SymmKey, they won't find it.

My recommendation is either to do the lazy fix, and at least mention the term `pass4SymmKey` in the documentation at that point, or what I feel is better, rename that variable to `pass4SymmKey` - because that's what it is and what every Splunk admin knows (although the CLI uses a different term for it).

**Comment by bb03** [comment]
@xpac1985 Thanks! We'll put the quick fix in shortly and have a conversation about renaming the variable. The resolution will depend on how strictly we want to adhere to the docs vs the internal configuration names.

**Comment by xpac1985** [comment]
I've put in feedback with Chris Gales' docs team, too, to have the docs changed/at least have them mention the pass4SymmKey term, too, so it's less confusing. I suggested they might ask the devs to add an alias for the `-secret` parameter as `-pass4symmkey` and after that change the docs to avoid confusion in the future.

**Comment by bb03** [comment]
Should be addressed in https://github.com/splunk/splunk-ansible/pull/311
@xpac1985 if you have any extra input on wording, ping me here.
