### ISSUE TITLE
Documentation is missing environment variables

### ISSUE THREAD

**Issue by mikedickey** [splunk/splunk-ansible#329]
[Advanced documentation](https://splunk.github.io/splunk-ansible/ADVANCED.html) is missing many environment variables supported by `environ.py` script (For example, `SPLUNK_APPS_URL`).

`grep os.environ environ.py`

Also is this really "advanced"? Seems like this file should be refactored a bit and made more accessible.

**Comment by bb03** [comment]
@mikedickey I agree.  We should reorganize our documentation to be clearer.

**Comment by edsale** [comment]
I second this issue.  An example that doesn't use docker and that works on the current version is desperately needed.

**Comment by nwang92** [comment]
Closing this - as of the 8.0.2 release, all the env vars should be documented now. 

@edsale I have some thoughts/experimental work to support the traditional, remote provisioning style of Ansible. I'll see if I can get a PR out next week.
