### ISSUE TITLE
cat: /opt/ansible/inventory/messages.txt: No such file or directory

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#34]
Seeing the following error output in the logs.

```
cat: /opt/ansible/inventory/messages.txt: No such file or directory
```

**Comment by lephino** [comment]
This is echoed if you have DEBUG on; I’m actually working on addressing this a bit with the sudo removal

**Comment by lephino** [comment]
Addressed in 
https://github.com/splunk/splunk-ansible/pull/37
