### ISSUE TITLE
Releases aren't being published to api.github.com

### ISSUE THREAD

**Issue by aidanSoles** [splunk/splunk-ansible#347]
I have automation that pulls a releases from `https://api.github.com/repos/<user>/<repo>/releases` on a parameterized basis. I'd like to do that for this repo, but for some reason it looks like https://api.github.com/repos/splunk/splunk-ansible/releases is empty. I'm not sure why that is, or if I'm missing something (like a `Do not publish to api.github.com` configuration option or something that's set for this repo), but any help/guidance would be appreciated. Much thanks. :)

**Comment by bb03** [comment]
@aidanSoles I'll talk with some of the folks here to see if there is a reason why it isn't being published. It's probably that we just never set the configuration option.

**Comment by aidanSoles** [comment]
Hi @bb03: thanks for responding man. I was able to circumvent the issue by hitting the tags endpoint instead (https://api.github.com/repos/splunk/splunk-ansible/tags?per_page=20), grabbing the `zipball_url` of the release in interest, then doing `GET` requests against the `zipball_url`'s to download the raw files.

I'm good to close the issue at this point! But I'm also cool if you want to keep it open for discussion. :)

**Comment by bb03** [comment]
Cool, I'll poke around a bit. We can probably make this easier to consume, but its a pretty low priority for us.

**Comment by aidanSoles** [comment]
No problem. And thanks for making/maintaining this repo. It's awesome. :)
