### ISSUE TITLE
Version check in enable_service.yml causes permission issue on $SPLUNK_HOME/etc/myinstall/splunkd.xml

### ISSUE THREAD

**Issue by scalatar** [splunk/splunk-ansible#359]
**CentOS**: 
CentOS Linux release 7.7.1908 (Core)

**Python**: 
2.7.5

**Ansible**:
```
ansible 2.10.0.dev0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/git/ansible/lib/ansible
  executable location = /root/git/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Assumptions**:

- Splunk installed as root
- Splunk intended to run as unprivileged user via systemd

The issue appears to be that a version check is done prior to `enable boot-start`. The result is that the file `splunkd.xml` is created under `$SPLUNK_HOME/etc/myinstall/splunkd.xml` and is not owned by the splunk user. As a result the Splunkd service does not start complaining about permissions to splunkd.xml.

**Steps to reproduce manually**:

1. Sudo to root `sudo su -`
2. Download splunk rpm to /tmp/splunk.rpm
3. Install splunk rpm `yum localinstall /tmp/splunk.rpm`
4. Check version of splunk `/opt/splunk/bin/splunk version --accept-license --answer-yes --no-prompt`
5. Verify that /opt/splunk/etc/myinstall/splunkd.xml exists and it not owned by splunk user `ls -l /opt/splunk/etc/myinstall/splunkd.xml`

A potential fix would be to ensure the Splunk version command is run as the splunk user. For example inside enable_service.yml the following code using `become_user` appears to resolve the problem:

`- name: "Retrieve Splunk version"
  become: yes
  become_user: "{{ splunk.user }}"
  command: "{{ splunk.exec }} version --accept-license --answer-yes --no-prompt"
  register: installed_splunk_version
  when: ansible_system is match("Linux")`

**Comment by nwang92** [comment]
Thanks for catching this! I merged a fix into develop - I have some other ideas on how to avoid making this `./bin/splunk` call in the future, but I'll chalk that up to future optimizations.
