### ISSUE TITLE
Indexer discovery for HWF and others requires SHC pass4SmmKey even when not using SHC

### ISSUE THREAD

**Issue by dexa187** [splunk/splunk-ansible#367]
I was trying to spin up a HWF docker container and found I needed to set SPLUNK_SHC_SECRET env in order to get the pass4SymmKey to show up in the HWF outputs.conf
This makes my config a bit confusing since im not using SHC.
https://github.com/splunk/splunk-ansible/blob/7bc2440ba971c6ba3db060597ec8adcb772ce4e0/roles/splunk_common/tasks/enable_forwarding.yml#L13

**Comment by nwang92** [comment]
Assigning to @alishamayor

**Comment by alishamayor** [comment]
@dexa187 Looks like it was setting the wrong pass4SymmKey, so I've updated it to use the indexer clustering one instead of the SHC one.
