### ISSUE TITLE
Ability to pass TLS certificates for other endpoints, e.g. hec, svc, etc.

### ISSUE THREAD

**Issue by aegershman** [splunk/splunk-ansible#372]
I'm using docker-splunk 7.3.4 (`splunk/splunk:7.3`)

How can I pass real certificates for the `hec` and `svc` endpoints to use? 

It appears you can control whether TLS for `hec` is active via `hec_enableSSL: <1,0>` (though it doesn't appear to be respected, see: https://github.com/splunk/splunk-ansible/issues/373), but not the _content_ of those certs. It always will present Splunk-generated certs.

I'm able to provide 'real' TLS certificate configuration for `splunk-web` as handled through `http_enableSSL_cert: <path>` and `http_enableSSL_privKey: <path>`, but not for any component endpoints, like `hec`, `s2s`, `svc`, etc.

Thank you!

EDIT: ah, maybe this is the key? will investigate more https://github.com/splunk/splunk-ansible/blob/0f9edc3b44c72337d16117f45bbd52b0d303140f/roles/splunk_common/tasks/s2s/configure_splunktcp_ssl.yml

```yml
# default.yml
...
splunk:
  s2s:
     ca: /path/xyz
     cert: /path/xyz
```

**Comment by nwang92** [comment]
Should have support for HEC and Splunkd certs in the next officially release, although it will also be available after this evening's `splunk/splunk:edge` push.
