### ISSUE TITLE
Setting `hec_enableSSL: 0` appears to still turn on splunk-generated certs

### ISSUE THREAD

**Issue by aegershman** [splunk/splunk-ansible#373]
Using docker-splunk @ `splunk/splunk:7.3`

When setting `hec_enableSSL: 0` in `default.yml`, it appears the HEC endpoint still serves up Splunk-generated certs; with `hec_enableSSL: 0`:

sending a request to `http://10.156.80.19:8088/services/collector` (notice, `http://`) results in

client:
```log
...
* Recv failure: Connection reset by peer
* Closing connection 0
```

server:
```log
02-01-2020 16:55:44.338 +0000 WARN  HttpListener - Socket error from 10.188.144.120:56623 while idling: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
```

and sending a request to `https://10.156.80.19:8088/services/collector` (notice, `https://`) still has the splunk-generated certs served:

```log
openssl s_client -connect 10.156.80.19:8088 -showcerts

Certificate chain
 0 s:/CN=SplunkServerDefaultCert/O=SplunkUser
   i:/C=US/ST=CA/L=San Francisco/O=Splunk/CN=SplunkCommonCA/emailAddress=support@splunk.com
-----BEGIN CERTIFICATE-----
MIIDMjCCAhoCCQD+XOT/21JOcTANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJV
UzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDzANBgNVBAoM
...
 1 s:/C=US/ST=CA/L=San Francisco/O=Splunk/CN=SplunkCommonCA/emailAddress=support@splunk.com
   i:/C=US/ST=CA/L=San Francisco/O=Splunk/CN=SplunkCommonCA/emailAddress=support@splunk.com
-----BEGIN CERTIFICATE-----
MIIDejCCAmICCQCNHBN8tj/FwzANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJV
UzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDzANBgNVBAoM
...
etc.
```

I'm trying to setup TLS with third-party signed certs on the HEC (see also: https://github.com/splunk/splunk-ansible/issues/372) but in lieu of that, trying to turn off HEC TLS in order to do HTTP proxy passthrough. But I can't seem to get the HEC to either turn off presenting it's TLS certs, or be able to pass my own third-party certs.

Thank you

possibly related: https://github.com/splunk/docker-splunk/issues/224

**Comment by nwang92** [comment]
https://github.com/splunk/splunk-ansible/issues/372 will require a bit more work, but we'll add that to our backlog.

This problem seems slightly independent though - configuring `hec_enableSSL: 0` should disable SSL on the HEC endpoint (port 8088). @alishamayor can you look into this?

**Comment by nwang92** [comment]
I realized there's a test for this in the docker-splunk repo: https://github.com/splunk/docker-splunk/blob/develop/tests/test_docker_splunk.py#L1137

My guess is if this is occuring, then the action of disabling SSL is not idempotent which is a bug we should address. Basically, if a container is started with `hec_enableSSL: 1` then the default.yml is changed to `hec_enableSSL: 0` and restarted, the change will not be reflected and instead the HEC endpoint still listens on 8088 using SSL.

**Comment by nwang92** [comment]
Closing this because I fixed it a while ago but forgot to update this issue. I'll also take a stab at #372 soon (hopefully)
