### ISSUE TITLE
`ansible_pre_tasks` and `ansible_post_tasks` definitions are missing

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#38]
It would appear that the `ansible_pre_tasks` and `ansible_post_tasks` definitions are missing from the final version of #31 , the following lines should be included:
```
    vars_scope["ansible_pre_tasks"] = os.environ.get("SPLUNK_ANSIBLE_PRE_TASKS") or getValueFromDEFAULTS("ansible_pre_tasks")
    vars_scope["ansible_post_tasks"] = os.environ.get("SPLUNK_ANSIBLE_POST_TASKS") or getValueFromDEFAULTS("ansible_post_tasks")
```

Unless I'm missing something.

**Comment by jmervine** [comment]
If you search the repo, you can see that they're not set:
https://github.com/splunk/splunk-ansible/search?q=ansible_pre_tasks&unscoped_q=ansible_pre_tasks

**Comment by lephino** [comment]
added to my open pr: https://github.com/splunk/splunk-ansible/pull/37

**Comment by jmervine** [comment]
@lephino I'm going to close this isn't the fix has been merged to `develop`.
