### ISSUE TITLE
Splunk install error on "develop" branch

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#40]
Oy! When building from the develop branch (for both github.com/splunk/docker-splunk and github.com/splunk/splunk-ansible), I'm getting the following error on deployment.

```
TASK [splunk_common : Install Splunk] ******************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'result.rc == 0' failed. The error was: error while evaluating conditional (result.rc == 0): 'dict object' has no attribute 'rc'"}
        to retry, use: --limit @/tmp/ansible-retry/site.retry
```

I verified that I'm seeing this error across multiple roles.

**Comment by arctan5x** [comment]
A pull request is on the way which includes this fix. I am closing this issue since the PR will be open soon.
