### ISSUE TITLE
service_name in splunk_defaults_linux.yml 

### ISSUE THREAD

**Issue by Mertox** [splunk/splunk-ansible#405]
In [get_facts.yml](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/get_facts.yml#L118) the service_name will be configured due to the fact that the [splunk_defaults_linux.yml](https://github.com/splunk/splunk-ansible/blob/develop/inventory/splunk_defaults_linux.yml#L91) contains this setting. This leads to the incorrect result that service_name will be "splunk" not "Splunkd.service". So far I got no detailed insights about the structure of the plays so I don't know where to mitigate the problem the best way.
My quick workaround is to set the service_name to "Splunkd.service" within /tmp/defaults/default.yml

**Comment by nwang92** [comment]
How are you running splunk-ansible? Are you using the wrapper-example as a template?

**Comment by Mertox** [comment]
I'm using my own wrapper playbook which is based on the wrapper-example. It kicks off splunk-ansible using the inventory script & reads the vars out of /tmp/defaults/default.yml:
`ansible-playbook -i inventory/environ.py site.yml` without `splunk.service_name` set
