### ISSUE TITLE
Additional playbook runs on cluster master will result in pushing bundle of disabled apps when custom apps in use

### ISSUE THREAD

**Issue by pgullette** [splunk/splunk-ansible#417]
I ran into a really strange issue that is now clear after understanding the process. I had a handful of times where my indexers in a distributed setup were for no apparent reason lacking indexes that were defined in an app that was pushed from the cluster master. The app existed on all the indexers in the proper slave-apps directory, and the contents of the contained indexes.conf was what I expected, however, the indexes were not showing up in the cluster master under indexer clustering. The title of this issue gives it away, but the reason is that the app was pushed to the indexers in a disabled state.

My app was definitely not disabled, so I knew it wasn't an oversight. I found that the cluster master role specifically has a task to disable installed apps which is where I started. It appears that task runs after all custom apps are installed, those custom apps are then copied from the installed location etc/apps/<app> to etc/master-apps/<app>, the bundle is pushed to all indexers, and then the installed apps on the cluster master are disabled. The disabling makes sense since it's likely custom apps should just be part of the bundle and not actually installed as part of the cluster master. This process works great and as expected the **FIRST** time the playbook runs.

Because of the order outlined above, and because of the repetition of the copy task in prepare_apps_bundle.yml, a subsequent run of the playbook will copy the now disabled app from etc/apps/<app> to the etc/master-apps/<app> location including the local/app.conf configured to disable the app. Even though the custom apps are installed/upgraded again during a subsequent playbook run, if the app is in a disabled state in etc/apps/<app>, it will remain in a disabled state after upgrade. Then the same copy happens to the etc/master-apps folder, and now a bundle is pushed containing disabled apps. And then the indexers magically no longer have index definitions that you swear should be there!

One way to correct this could be to uninstall any custom apps before installing them to ensure no existing modifications stick around. This would not be a good idea for non-cluster master instances, but I _think_ it would be ok for cluster master. Another possibly uglier solution could be to forcefully remove the local/app.conf disabled stanza, but that makes some assumptions that could be bad. I guess it's possible someone could want a bundle to include a disabled app, and a forceful removal could make that person mad. It seems like any other safe approach that doesn't first uninstall the custom app before reinstall would require some additional context about the original app and its contents which would be ugly and complex.

I may write up a PR with the uninstall app first option, but I'd love to see if anyone else has other things I've not considered with this potential fix.

**Comment by nwang92** [comment]
I'm going to close this, but feel free to re-open if you encounter any issues with the new changes
