### ISSUE TITLE
Automated way to setup up a standalone monitoring console

### ISSUE THREAD

**Issue by dglauche** [splunk/splunk-ansible#434]
After taking a closer look into this project it seems like there is no way to spin up a distributed monitoring console? Did I miss something here or did you choose to not include it on purpose/got not time/needs so far?

In case of search head cluster, the DMC_FORWARDER_MONITORING feature does not work because the MC app gets disable after configuring the nodes as SHC members.

**Comment by dglauche** [comment]
To add something here: In case of search head cluster, the DMC_FORWARDER_MONITORING feature does not work because the MC app gets disable after configuring the nodes as SHC members.

**Comment by nwang92** [comment]
It's currently not supported yet. We plan on making the distributed monitoring console a separate role and hopefully it's something we can get done soon. But this feature has been [asked for before](https://github.com/splunk/docker-splunk/issues/313), so maybe our PMs will prioritize it a bit higher :)

**Comment by nwang92** [comment]
DMC is now included as part of https://github.com/splunk/splunk-ansible/pull/501. This new `splunk_monitor` role acts as a standalone search head over all instances in a deployment, and it automatically enables DMC in distributed mode with the peers/groups set appropriately.
