### ISSUE TITLE
Missing documentation for some configuration parameters in default.yml

### ISSUE THREAD

**Issue by jenipherc** [splunk/splunk-ansible#435]
The following list is generated based on the default.yml from wrapper example
`docker run -it splunk/splunk:8.0.3 create-defaults`

- splunk.multisite_*
- root_endpoint
- service_name
- retry-delay
- wait_for_splunk_retry_num
- splunk.allow_upgrade
- docker
- java_*
- dmc_*
- ansible_connection
- ansible_environment
- splunk.build_url_bearer_token
- splunk.set_search_peers

**Comment by alishamayor** [comment]
Thanks for the heads up! Will take care of it in an upcoming docs update 🤙
