### ISSUE TITLE
Ability to set different pass4SymmKey for Indexer Discover from the Clustering Pass4SymmKey

### ISSUE THREAD

**Issue by sharkannon** [splunk/splunk-ansible#461]
Just revisiting this module, as I attempted to use it about a year ago, but couldn't quite do what I needed to do.  Things are looking a lot better (thank. you guys), but still finding some tweaks that could be useful to fix.

Currently we have our Cluster pass4SymmKey for setting up the indexers set to a different pass4SymmKey that the forwarders use for Indexer Discovery.  Unfortunately the code only allows for 1 key to be set using the splunk.idxc.pass4SymmKey param (Which sets the Key for both Indexer discovery and clustering).

it would be nice to be able to set each independently of each other, as they are two different functions.

**Comment by nwang92** [comment]
We got this ask internally too, so we're on it!

**Comment by nwang92** [comment]
Done, should be available as `splunk.idxc.discoveryPass4SymmKey` going forward. Will add a test in the docker-splunk project for this
