### ISSUE TITLE
Why are so many configuration options hidden behind "first_run"?

### ISSUE THREAD

**Issue by sharkannon** [splunk/splunk-ansible#476]
There seems to be a lot of configuration's that appear to be hidden behind "first_run", so once splunk is up and running, they will never get run again.

An example of this is SPLUNK_LICENSE_URI.  If the splunk.secret file exists (your condition for first_run), then ansible never applies the license again. 

Sure you can apply the license through the UI, but if you're trying to make it so that configurations are source controlled, and dynamic, it makes it very hard.

That's just one example, though I can come up with more if needed, for now I am asking the question before I start putting in bug/feature tickets.

**Comment by nwang92** [comment]
The origin of these plays were from an internal project to deploy ephemeral Splunk instances on-demand. There's a few idempotence issues lingering but we've been working on clearing out those cobwebs. Feel free to call them out!

**Comment by nwang92** [comment]
Closing this out because this specific use case is addressed, but I think there are still cases of this happening in other areas that I'll go prune.
