### ISSUE TITLE
When specifying SPLUNK_TAIL_FILE is not reflected in the message at the end of entrypoint.sh

### ISSUE THREAD

**Issue by mhoogcarspel-splunk** [splunk/splunk-ansible#499]
Related to https://github.com/splunk/docker-splunk/pull/163

`
echo Ansible playbook complete, will begin streaming var/log/splunk/splunkd_stderr.log
`
should probably be something like this to reflect that we're tailing a different file:

```
	if [ -z "$SPLUNK_TAIL_FILE" ]; then
		echo Ansible playbook complete, will begin streaming var/log/splunk/splunkd_stderr.log
	else
		echo Ansible playbook complete, will begin streaming ${SPLUNK_TAIL_FILE} 
	fi
```
(not tested, just freehand code)

**Comment by nwang92** [comment]
Good call, I can certainly add that
