### ISSUE TITLE
Option to Disable New User Tour

### ISSUE THREAD

**Issue by stjohnjohnson** [splunk/splunk-ansible#514]
Can we please have an option to turn off the new user tour (that happens on almost every page)?

**Comment by nwang92** [comment]
@TheCamNelson let's go over this in our sync today, should be pretty straightforward and similar to how we approached DMC.

**Comment by nwang92** [comment]
Done in this PR: https://github.com/splunk/splunk-ansible/pull/522

This should be available in the next image release (8.0.6?) or the nightly `splunk/splunk:edge` images. Adding `-e SPLUNK_DISABLE_POPUPS=true` should do the trick.
