### ISSUE TITLE
Outputs.conf must be created before splunk starts

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-ansible#520]
When outputs.conf is not created prior to the start of splunk buckets will be created this confuses multiple things including the MC and can cause loss of debugging data.

**Comment by nwang92** [comment]
I believe this is covered already? See https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/main.yml#L124-L130

**Comment by rfaircloth-splunk** [comment]
Doesn't seem to be the CM and SH peer roles have buckets in a newly deployed cluster via operator if outputs was present before FTR this would not be true

**Comment by nwang92** [comment]
Hmm the only reason I could see that happening might be the Docker image version? The change made to move outputs.conf before Splunk start was done here: https://github.com/splunk/splunk-ansible/pull/453, so it should be available in images >= 8.0.3?

**Comment by nwang92** [comment]
Going to close this issue as the `enable_forwarding.yml` task does run prior to `start_splunk.yml`:
https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/main.yml#L115-L125
