### ISSUE TITLE
Files not available in tag 8.0.3

### ISSUE THREAD

**Issue by jenipherc** [splunk/splunk-ansible#530]
https://github.com/splunk/splunk-ansible/tree/8.0.3/roles/splunk_common/vars 
isn't available for tag 8.0.3

**Comment by nwang92** [comment]
I think this is expected. The `8.0.3` tag was added onto [this commit](https://github.com/splunk/splunk-ansible/commit/373daf1) made on 4/14/2020. The `vars` directory was added as part of [this commit](https://github.com/splunk/splunk-ansible/commit/b7aabac05e22e8dfad03ef2f775ee6d289475c2f) which was made on 4/17/2020.
