### ISSUE TITLE
Ansible plays needed for enterprise release

### ISSUE THREAD

**Issue by forktheweb** [splunk/splunk-ansible#54]
- We need a SAML configuration/ ACLs  ansible play feature
- We need an index creation ansible play feature
- We need alert configuration management for pagerduty for indexers and search heads

This is critical to our enterprise deployment of Splunk, because we need these features to be deterministic through the use of docker-compose 2.0 environment variables.

Thank you

**Comment by forktheweb** [comment]
The use case is that we are hosting splunk for many groups, and each group could have different requirements.  i.e.- They need their own index mapped to an HEC.   Then we need to programatically set up a role mapping so they can only search their index.

**Comment by nwang92** [comment]
Based on your use-case, I think the best way to manage a series of varied configuration files would be an app. For instance, something like:
```
splunk_app_forktheweb/
    default/
        app.conf
        authentication.conf
        inputs.conf
        savedsearches.conf
```
where the above configs expose the following parameters:
* `app.conf`: generic name and version information
* `authentication.conf`: setup SAML - you can configure SAML via the UI, and copy the same configuration file for future persistence. You may also need a `web.conf`.
* `inputs.conf`: create HEC tokens which write to specific indexes. You may also need an `indexes.conf`.
* `savedsearches.conf`: create saved searches and alerts

I'm not sure about the topology + environment you're looking to create, but hypothetically, let's say you're creating a heavy forwarder pool (via docker/k8s) to connect to some remote indexers (EC2). It's possible to create the HEC tokens on the heavy forwarders without creating the same HEC tokens on the indexers. You *do* need to make sure that the index to which the HEC endpoint writes does exist on your indexer tier.

**Comment by forktheweb** [comment]
Thanks for your response on this.  We actually are doing an app in manual configuration for some things.  Mainly the HEC setup and Index setups.   But we don't know how to deploy our app with splunk-ansible.  Is there a hook for that. 

We are using docker-compose in an orchestrated environment called Rancher 1.6 / cattle.
We currently configure many aspects in the compose using environment variables.   

It would be ideal if we could use an API to publish the apps, perform authentication/ role/ saml configuration, add distributed search peers, add indexer clusters, etc. because I'm not sure this will be very easy to do with ansible plays strictly.

**Comment by nwang92** [comment]
There is. If you're app is packaged and available via some web URL, on the container side you can pass in:
```
$ docker run -d -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -e SPLUNK_APPS_URL=http://webserver/app.tgz -p 8000 splunk/splunk
```

Additionally, if you're just using Ansible directly, you can define this in your defaults.yml:
```
splunk:
    apps_locations: 
        - "http://webserver/app.tgz"
    ...
```

Regarding your last point, this set of Ansible playbooks is very much capable of bringing up a distributed search + index cluster environments. I'd check out the examples of how this is done in this example here: https://github.com/splunk/docker-splunk/blob/develop/test_scenarios/3idx3sh1cm.yaml

**Comment by forktheweb** [comment]
That's great to know about the app packaging deployment.   I'm sure we can do that in the docker-compose then too.  

The test scenario you've provided is what we are currently using for each cluster.  But imagine, we have multiple sites/environments because we are running a centralized search head.  So we have to connect the external indexer clusters with our central clusters.  They clusters are in multiple regions.   

That's what we would need to do with ansible, and it appears there are still some manual steps setting up distributed search and setting up the indexer cluster search peers.

**Comment by nwang92** [comment]
Hmm I think I understand, but I have a few clarifying questions:
* Are you bringing up all these environments via Docker? Or is your architecture in a mixed-mode with some Docker/some physical machines?
* Are you indexer clusters setup via Docker and your centralized search head is some bare-metal machine/VM?
* Vice versa of the above - is your search head a Docker instance and your indexer clusters bare-metal/VM?

It should also be possible to connect search heads and indexers cross-regions/cross-cluster, however that may have some trade-offs in network performance and/or additional cost.

**Comment by forktheweb** [comment]
Each "environment" is a group of 3 Virtual machines in an isolated network.  Rancher uses an overlay network so that orchestration can occur, and "cattle" agents are on all these VMs.   So you can think of each environment as a single indexer cluster setup in various regions,   Similar to a k8s cluster. One of those clusters contains our primary search-head that has the URL that all the other users use to search their own clusters.

We know it is definitely possible to connect clusters in multiple regions using this method, we just want to know if there is an easy API call we can make to add search peers and indexer clusters to the primary environment.  

I did notice we can add in the license URL to the indexers with this env var:
SPLUNK_LICENSE_URI=http://company.com/path/to/splunk.lic

So that answers that question.

It looks like the last sticking points are just automating the user/role/saml modifications, and setting up alerts.  Do you have an reference docs on how to do that through the api?   Or can some of this be done in splunk-ansible?

**Comment by akulbe** [comment]
Can this be used to install Splunk on VMs or is it primarily designed for containers?

**Comment by lephino** [comment]
Follow my wrapper example on how to use this with anything, even bare metal:  https://github.com/splunk/splunk-ansible/tree/develop/wrapper-example

**Comment by nwang92** [comment]
Going to close this as we do have the wrapper-example in this repo to show how these playbooks can be used with VMs/bare-metal machines. We'll incorporate the wrapper-example into our docs so it's more clear to new users because we do get this query a lot. The playbooks here are primarily meant to be used in conjunction with https://github.com/splunk/docker-splunk, although long-term it may be nice to support both local- and remote-connection more seamlessly.
