### ISSUE TITLE
HIDE_PASSWORD=false doesn't appear to work

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#56]
Hey, super small, boarder line pedantic, but... when I set `HIDE_PASSWORD=false`, I'm still getting censored, e.g.
```
TASK [Download post-setup playbooks] *******************************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
...ignoring
```
Looking at the following, I'd assume I'd see the output...

https://github.com/splunk/splunk-ansible/blob/f679cd4a20765bd35f4adf341122c7d714011f7f/inventory/environ.py#L101

**Comment by jmervine** [comment]
As an aside, it doesn't seem necessary to hide logs for the following, as `uri` doesn't appear to show password on error...

https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/wait_for_splunk_instance.yml#L16

**Comment by arctan5x** [comment]
Would you set DEBUG=true and copy us the variables? I agree with your assessment. That line in environ.py is the only place we control HIDE_PASSWORD so I assume that it should be false.

**Comment by jmervine** [comment]
I’ll do that next time I’m at my laptop. Maybe not until Wednesday though. 

I would assume the same from looking at the code.

**Comment by jmervine** [comment]
I’m not able to reproduce this. I’ll reopen if I see it again.
