### ISSUE TITLE
Splunk role not respected when set in default.yml

### ISSUE THREAD

**Issue by dp-42** [splunk/splunk-ansible#577]
Hello,

according to the [default.yml.spec.md](https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md) you can define the role of the resulting instance using the `splunk.role` variable.
However, this variable is not respected by the merge logic.

https://github.com/splunk/splunk-ansible/blob/6f94c3523957a79286dcbee97248791652fb74fe/inventory/environ.py#L126

As far as understand the merge logic reads the environment variable `SPLUNK_ROLE` and sets `splunk_standalone` as a fallback,
Therefore, regardless what I define in my `default.yml` I always have to set the environment variable as well.

I assume this is not intended behavior?

**Comment by nwang92** [comment]
Ah, this is likely because the docker images set `SPLUNK_ROLE=splunk_standalone`, so the `default.yml` won't pick it up. Let me see if there's an alternative here.

**Comment by nwang92** [comment]
Done in linked PR
