### ISSUE TITLE
Set Splunk secret

### ISSUE THREAD

**Issue by dLabsMarijnB** [splunk/splunk-ansible#58]
#51 #52 #50 #22 

Setting the Splunk secret is a key functionality we use.

While yes, it can break your Splunk when you change your splunk secret after shutting down and starting up your container or splunk instance.  This is normally not something you would change on a regular basis.

The way it was implemented was, if it was empty or undefined, it should leave it to the default auto generation behaviour of Splunk.  If it is defined, it should be set before splunk launch.

In order to restore the task, which change would you like to see?

**Comment by nwang92** [comment]
Actually the error I saw with secret + SHC was actually in the SHC secret propagation between cluster members + deployer, I don't think this is (directly) related to the functionality of what gets set in `${SPLUNK_HOME}/etc/auth/splunk.secret`

**Comment by dLabsMarijnB** [comment]
We could potentially just introduce a new parameter: FORCE_SECRET
In case the secret exists, don't write it.
If it exists and force_secret is set, overwrite it.
In case it does not exist, create it.

I guess that would cover pretty much every scenario?

**Comment by nwang92** [comment]
Taking a cursory look at this: https://answers.splunk.com/answers/639815/what-is-the-splunksecret-file-and-is-it-possible-t.html, I'm not sure I'd want to support overwriting splunk.secret at all. Basically, changing the value in splunk.secret requires you to go through all conf files in Splunk, editing files with plaintext passwords, and restarting to re-encrypt. 

Given we can't know what apps or local configurations or user-defined passwords would be, I don't think it's safe to touch this parameter. If we do support allowing a user-defined splunk.secret, this should come with extreme caution such that:
* You can set splunk.secret on the initial creation of your Splunk deployment
* You can **never** change splunk.secret for an existing Splunk deployment - if you do, we recommend you go through the steps outlined in that Splunk Answers article manually or rebuild from scratch.
