### ISSUE TITLE
Use ansible lint

### ISSUE THREAD

**Issue by kylesloan** [splunk/splunk-ansible#586]
https://github.com/ansible-community/ansible-lint has become somewhat industry standard for ansible lint/checking.

**Comment by nwang92** [comment]
I believe we already are using `ansible-lint` as part of the repo/CI checks: https://github.com/splunk/splunk-ansible/blob/develop/Makefile#L15

Additionally, a lot of the testing is driven by [molecule](https://github.com/ansible-community/molecule) which I believe also uses ansible-lint internally.
