### ISSUE TITLE
More logging?

### ISSUE THREAD

**Issue by jenipherc** [splunk/splunk-ansible#608]
It would be nice to have some logging built in and be able to turn it on or off if debug is needed.
An example I would like to have is to have the ability to print out app_url in here
https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/install_apps.yml#L34

When you have a lot of apps to download and then install, it is a bit difficult to know which one has been downloaded (ansible play changed) or which one has been installed. 

Thank you.

**Comment by nwang92** [comment]
There are ways to leverage the available Ansible configuration options that are exposed as environment variables for this. Specifically, maybe https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-verbosity?

I think this can be used like:
```bash
$ export ANSIBLE_VERBOSITY=3
$ ansible-playbook ...
```
or
```bash
$ ANSIBLE_VERBOSITY=3 ansible-playbook ...
```
