### ISSUE TITLE
Support set client name for deployment client mode

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-ansible#612]
Some customers use "client name" in deploymentclient.conf rather than host to indicate to the DS which config groups should be applied. This is difficult to set once the container is running but could be easily set from an expanded env variable

for example 
```
SPLUNK_DEPLOYMENT_CLIENT_NAME=foo
SPLUNK_DEPLOYMENT_CLIENT_NAME=${POD_NS}_${POD_NAME}
```

**Comment by nwang92** [comment]
This should be available in `splunk/splunk:edge` and in future Docker images >= 8.1.3
