### ISSUE TITLE
SH: Support Multiple Clusters

### ISSUE THREAD

**Issue by dp-42** [splunk/splunk-ansible#614]
Hello,

I have setup an Indexer cluster (including an Cluster Manager) and also my Search Head is connected to the Indexer Cluster (via CM).
Now, I have the use case that I want to setup a second Indexer Cluster. Therefore my Search Head needs to connect to the second Indexer cluster as well. 

Unfortunately, this is currently not supported - at least, that´s how I understood it:

The corresponding code should be [roles/splunk_search_head/tasks/setup_multisite.yml](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_search_head/tasks/setup_multisite.yml).
`splunk.multisite_master` is a simple string, therefore it is not possible to add multiple masters.

So I would like to ask for adding this feature - what is your opinion on that use case?

I would also be interested in contributing this if you think it make sense. My initial idea (without actually testing it (yet)) would be to turn `splunk.multisite_master` to an array and iterate over all the configured clusters. Unfortunately, the variable is also used for the indexer role and here I think it not possible that an indexer joins multiple clusters, so that is something that needs to be considered...

Kind regards,
Daniel

**Comment by nwang92** [comment]
Would this be possible through https://github.com/splunk/splunk-ansible/issues/464?

**Comment by dp-42** [comment]
Hi @nwang92 

thank you for your fast reply.

It took me some time to check the mentioned `auxiliary_cluster_masters` setting. 
Unfortunately, I am running Multisite Clusters - so this does not work for me.

I ended up building the required settings blocks using the `conf` [section](https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md#configuration-files). That worked for me.

Many thanks!
Daniel
