### ISSUE TITLE
Installation of apps through Splunk app base URL fails 

### ISSUE THREAD

**Issue by kumarajeet** [splunk/splunk-ansible#618]
Installation of apps using splunkbase URL is failing with python issue.

**Use following lines your default.yml file to point the apps_location to a splunk base app.**

splunk:
  splunkbase_username: your user id
  splunkbase_password: your password
  apps_location:
    - https://splunkbase.splunk.com/app/978/release/1.1/download

**The ansible playbook fails with the following error:**

[WARNING]: * Failed to parse /opt/ansible/inventory/environ.py with script
plugin: Inventory script (/opt/ansible/inventory/environ.py) had an execution
error: Traceback (most recent call last): File
"/opt/ansible/inventory/environ.py", line 821, in <module> main() File
"/opt/ansible/inventory/environ.py", line 807, in main
getSplunkInventory(inventory) File "/opt/ansible/inventory/environ.py", line
95, in getSplunkInventory inventory["all"]["vars"] = getDefaultVars()
File "/opt/ansible/inventory/environ.py", line 147, in getDefaultVars
getSplunkbaseToken(defaultVars) File "/opt/ansible/inventory/environ.py",
line 354, in getSplunkbaseToken splunkbase_token =
re.search("<id>(.*)</id>", output, re.IGNORECASE) File
"/usr/lib/python3.7/re.py", line 185, in search return _compile(pattern,
flags).search(string) TypeError: cannot use a string pattern on a bytes-like
object
[WARNING]: * Failed to parse /opt/ansible/inventory/environ.py with ini
plugin: /opt/ansible/inventory/environ.py:16: Expected key=value host variable
assignment, got: __future__
[WARNING]: Unable to parse /opt/ansible/inventory/environ.py as an inventory
source 

This is is possibly linked with Python3.7 regular expression not able to parse HTML output
It works fine with python2.x if I run snippet of same code from getSplunkbaseToken method.

**More details:**

Look into environ.py: getSplunkbaseToken(..) 

Following line will  post a login URL to splunkbase to fetch the authentication token that can be used for next steps.

requests.post("https://splunkbase.splunk.com/api/account:login/", data=

{"username": vars_scope["splunkbase_username"], "password": vars_scope["splunkbase_password"]}
) ...

Next we get the output from response.

output = resp.content

The expected output is (extracted through a local script using python 2.x)

 <?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
 <title>Authentication Token</title>
 <updated>2021-03-28T20:03:10.129101+00:00</updated>
 <id>n5cjs8p06********gk8p6m4ydjlg50</id>                  <------------------this is the token
</feed>
 

Then following statement will try to get token 

splunkbase_token = re.search("<id>(.*)</id>", output, re.IGNORECASE)

It fails - the reason is that in python3.x (which I assume is now default used phython in ansible), the resp.content is a bytes-like data as compare to text data in python2.x

You may have to decode the output before running re.search. Something like below. this will decode assuming response was in UTF-8, I believe.

splunkbase_token = re.search("<id>(.*)</id>", output.decode(), re.IGNORECASE)

**Comment by nwang92** [comment]
This should be resolved by https://github.com/splunk/splunk-ansible/pull/610. Are you using `splunk/splunk:edge` or `splunk/splunk:8.1.3`?

**Comment by kumarajeet** [comment]
Thanks @nwang92 . #610 seems like having the fix. As far as I know, I am using splunk/splunk:8.1.3.
