### ISSUE TITLE
Crucial configuration error for search head clustering

### ISSUE THREAD

**Issue by roelblyweert** [splunk/splunk-ansible#67]
There is a critical issue with the last task in the splunk-ansible/roles/splunk_search_head/tasks/search_head_clustering.yml file. This performs the action to configure all search head cluster nodes as deployment client towards the deployer. The deployment server and deployer functionality get mixed, so you get into a situation where potentially 2 processes are managing the same target client. I have seen entire search head clusters going down due to similar situations, so this something to get rid of.

**Comment by dLabsMarijnB** [comment]
Indeed, deploy-poll actually sets the deployment server, not the deployer.
The task should simply be removed from SHC.
