### ISSUE TITLE
Seems like issue in set_config_stanza.yml

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-ansible#751]
Hello, 

while working with splunk-operator (https://github.com/splunk/splunk-operator/issues/1212), looks like i found logical issue somehwere there:
https://github.com/splunk/splunk-ansible/blob/076537346517070a222e37bd2b3a87c528a14eb9/roles/splunk_common/tasks/set_config_stanza.yml#L20C1-L21C1

problem: when pod restars, value is empty, which creates broken config. 

possible solution: check if key with value already exist.

**Comment by iaroslav-nakonechnikov** [comment]
https://github.com/splunk/splunk-ansible/pull/736

**Comment by yaroslav-nakonechnikov** [comment]
issue still in 9.1.1

**Comment by adityapinglesf** [comment]
thanks @yaroslav-nakonechnikov for raising the request and suggesting the fix. I am working with splunk-operator team to test the fix.

**Comment by martindimitrov-taulia** [comment]
I face the same issue. Thanks for working on it!

**Comment by yaroslav-nakonechnikov** [comment]
this one looks like fixed.
