### ISSUE TITLE
Scripts fail on "Wait for splunkd management port"

### ISSUE THREAD

**Issue by tod-uma** [splunk/splunk-ansible#770]
when using this to install a universal forwarder 9.1.2, the scripts fail on "Wait for splunkd management port". This is because now by default the forwarder doesn't actually listen on a tcp  managment port on linux, it uses a socket file instead. By default the mgmtMode is set to auto, which means it does not listen on a tcp port. The scripts need to be updated to find a different way to know when the splunkd is up. 

See mgmtMode in:
https://docs.splunk.com/Documentation/Splunk/9.1.2/Admin/Serverconf

Error when running:

TASK [splunk_common : Wait for splunkd management port] *******************************************************************************************************************************
fatal: [test-forwarder.test.test]: FAILED! => changed=false 
  elapsed: 300
  msg: Timeout when waiting for 127.0.0.1:8089

**Comment by adityapinglesf** [comment]
can you share more about the environment you face this error?

**Comment by tod-uma** [comment]
Yes, I'm using the Ansible scripts to install the universal forwarder on a new OEL9 VM. It uses the Splunk provided RPM to install.

**Comment by adityapinglesf** [comment]
we released new updates for 9.1.x to support unix domain socket files. that should resolve this issue. feel free to comment if you still run into errors

**Comment by tod-uma** [comment]
I have gotten it to work in my environment with the development branch. Thank you for the fix.
