### ISSUE TITLE
Heavy forwarder deployment client

### ISSUE THREAD

**Issue by stephenmuss** [splunk/splunk-ansible#85]
Hi there,

Having a dig around the source code, it looks like it is only possible to set a universal forwarder as a deployment client. Is it possible to have the same deploy-poll command available for a heavy forwarder build as well? Is there any reason why you wouldn't do this?

Cheers

**Comment by lephino** [comment]
Think this is just an oversight on our part, we'll get it fixed and added.

**Comment by jmeixensperger** [comment]
Here's the relevant PR: #120

**Comment by stephenmuss** [comment]
Good news. Thanks @lephino.

**Comment by jmeixensperger** [comment]
@stephenmuss feel free to re-open if you are still having issues.
