### ISSUE TITLE
UF uses wrong port in "setup deployment server" plays

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-ansible#92]
Hey team, 

When setting the `SPLUNK_DEPLOYMENT_SERVER` variable, the Ansible play uses the `s2s_port` instead of the `svc_port`

```
command: "{{splunk.exec}} set deploy-poll {{ splunk.deployment_server }}:{{ splunk.s2s_port }} -auth admin:{{ splunk.password }}"
```

should be:

```
command: "{{splunk.exec}} set deploy-poll {{ splunk.deployment_server }}:{{ splunk.svc_port }} -auth admin:{{ splunk.password }}"
```

https://docs.splunk.com/Documentation/Splunk/7.2.3/Updating/Configuredeploymentclients#Use_the_CLI

Also not sure if it is expected that the "add deployment server" task is duplicated here??

https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_universal_forwarder/tasks/main.yml#L7

**Comment by nwang92** [comment]
Done with #94
